export const ProfileStyles = {
  container: {
    display: 'flex',
    minHeight: '100vh',
    backgroundColor: '#f8f9fa',
    padding: '20px',
  },
  profileCloud: {
    backgroundColor: 'white',
    borderRadius: '30px',
    padding: '20px',
    boxShadow: '0 0 10px rgba(0,0,0,0.1)',
    margin: '10px',
    width: '300px',
    flexShrink: 0,
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
  },
  playlistCloud: {
    backgroundColor: 'white',
    borderRadius: '30px',
    padding: '15px',
    boxShadow: '0 0 10px rgba(0,0,0,0.1)',
    margin: '10px',
    transition: 'all 0.3s ease',
    cursor: 'pointer',
    flexGrow: 1,
    maxHeight: '100px',
    overflow: 'hidden',
  },
  expandedCloud: {
    flexGrow: 3,
    backgroundColor: '#e6f2ff',
    maxHeight: 'none',
    padding: '20px',
  },
  title: {
    fontSize: '1.5rem',
    marginBottom: '20px',
    color: '#007bff',
  },
  image: {
    width: '150px',
    height: '150px',
    borderRadius: '50%',
    marginBottom: '20px',
    objectFit: 'cover',
  },
  imagePlaceholder: {
    width: '150px',
    height: '150px',
    borderRadius: '50%',
    marginBottom: '20px',
    backgroundColor: '#e9ecef',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: '#6c757d',
    fontSize: '14px',
  },
  info: {
    marginBottom: '10px',
    color: '#666',
  },
  playlistTitle: {
    fontSize: '1.2rem',
    color: '#007bff',
    marginBottom: '10px',
  },
  playlistImage: {
    width: '100%',
    maxWidth: '300px',
    height: 'auto',
    borderRadius: '10px',
    marginBottom: '10px',
  },
  playlistDescription: {
    color: '#666',
    fontSize: '0.9rem',
    marginBottom: '15px',
  },
  expandedInfo: {
    marginTop: '10px',
    color: '#007bff',
  },
  trackListTitle: {
    fontSize: '1rem',
    color: '#007bff',
    marginBottom: '10px',
  },
  trackList: {
    listStyleType: 'none',
    padding: 0,
  },
  trackItem: {
    fontSize: '0.9rem',
    marginBottom: '5px',
  },
  expandButton: {
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    padding: '5px 10px',
    borderRadius: '5px',
    cursor: 'pointer',
    marginTop: '10px',
  },
  logoutButton: {
    backgroundColor: '#dc3545',
    color: 'white',
    border: 'none',
    padding: '10px 15px',
    borderRadius: '5px',
    cursor: 'pointer',
    marginTop: '20px',
    transition: 'background-color 0.3s',
  },
};